var veganFoodArray = [
  {
    name: "Vegan Margherita Pizza",
    category: "Vegan Pizza",
    estimatedPrice: 18.00,
    estimatedOrders: 100,
    likes: 90,
    picture: "https://example.com/vegan_pizza.jpg",
  },
  {
    name: "Falafel Wrap",
    category: "Vegan Sandwich",
    estimatedPrice: 10.00,
    estimatedOrders: 120,
    likes: 110,
    picture: "https://example.com/falafel_wrap.jpg",
  },
  {
    name: "Tofu Stir Fry",
    category: "Vegan Asian",
    estimatedPrice: 15.00,
    estimatedOrders: 130,
    likes: 115,
    picture: "https://example.com/tofu_stir_fry.jpg",
  },
  {
    name: "Vegan Burrito",
    category: "Vegan Mexican",
    estimatedPrice: 14.00,
    estimatedOrders: 150,
    likes: 120,
    picture: "https://example.com/vegan_burrito.jpg",
  },
  {
    name: "Vegan Sushi Roll",
    category: "Vegan Japanese",
    estimatedPrice: 16.00,
    estimatedOrders: 110,
    likes: 100,
    picture: "https://example.com/vegan_sushi.jpg",
  },
  {
    name: "Vegan Burger",
    category: "Vegan Fast Food",
    estimatedPrice: 13.00,
    estimatedOrders: 160,
    likes: 140,
    picture: "https://example.com/vegan_burger.jpg",
  },
  {
    name: "Vegan Pasta Primavera",
    category: "Vegan Italian",
    estimatedPrice: 17.00,
    estimatedOrders: 105,
    likes: 95,
    picture: "https://example.com/vegan_pasta.jpg",
  },
  {
    name: "Vegan Paella",
    category: "Vegan Spanish",
    estimatedPrice: 20.00,
    estimatedOrders: 90,
    likes: 85,
    picture: "https://example.com/vegan_paella.jpg",
  },
  {
    name: "Vegan Pad Thai",
    category: "Vegan Thai",
    estimatedPrice: 14.50,
    estimatedOrders: 115,
    likes: 105,
    picture: "https://example.com/vegan_pad_thai.jpg",
  },
  {
    name: "Vegan Quinoa Salad",
    category: "Vegan Salads",
    estimatedPrice: 10.50,
    estimatedOrders: 120,
    likes: 110,
    picture: "https://example.com/vegan_quinoa_salad.jpg",
  },
  {
    name: "Vegan Tofu Scramble",
    category: "Vegan Breakfast",
    estimatedPrice: 9.00,
    estimatedOrders: 130,
    likes: 120,
    picture: "https://example.com/vegan_tofu_scramble.jpg",
  },
  {
    name: "Vegan Chocolate Cake",
    category: "Vegan Desserts",
    estimatedPrice: 8.00,
    estimatedOrders: 140,
    likes: 130,
    picture: "https://example.com/vegan_chocolate_cake.jpg",
  },
];
