var nonVeganFoodArray = [
  {
    name: "Pepperoni Pizza",
    category: "Pizza",
    estimatedPrice: 15.00,
    estimatedOrders: 200,
    likes: 180,
    picture: "https://example.com/pepperoni_pizza.jpg",
  },
  {
    name: "Chicken Caesar Wrap",
    category: "Sandwich",
    estimatedPrice: 10.00,
    estimatedOrders: 150,
    likes: 130,
    picture: "https://example.com/chicken_caesar_wrap.jpg",
  },
  {
    name: "Beef Stir Fry",
    category: "Asian",
    estimatedPrice: 16.00,
    estimatedOrders: 140,
    likes: 120,
    picture: "https://example.com/beef_stir_fry.jpg",
  },
  {
    name: "Pulled Pork Burrito",
    category: "Mexican",
    estimatedPrice: 14.00,
    estimatedOrders: 160,
    likes: 140,
    picture: "https://example.com/pulled_pork_burrito.jpg",
  },
  {
    name: "California Roll Sushi",
    category: "Japanese",
    estimatedPrice: 16.00,
    estimatedOrders: 120,
    likes: 100,
    picture: "https://example.com/california_roll_sushi.jpg",
  },
  {
    name: "Cheeseburger",
    category: "Fast Food",
    estimatedPrice: 13.00,
    estimatedOrders: 180,
    likes: 150,
    picture: "https://example.com/cheeseburger.jpg",
  },
  {
    name: "Spaghetti Carbonara",
    category: "Italian",
    estimatedPrice: 16.00,
    estimatedOrders: 130,
    likes: 115,
    picture: "https://example.com/spaghetti_carbonara.jpg",
  },
  {
    name: "Seafood Paella",
    category: "Spanish",
    estimatedPrice: 22.00,
    estimatedOrders: 90,
    likes: 80,
    picture: "https://example.com/seafood_paella.jpg",
  },
  {
    name: "Chicken Pad Thai",
    category: "Thai",
    estimatedPrice: 15.50,
    estimatedOrders: 140,
    likes: 125,
    picture: "https://example.com/chicken_pad_thai.jpg",
  },
  {
    name: "Caesar Salad",
    category: "Salads",
    estimatedPrice: 12.50,
    estimatedOrders: 150,
    likes: 135,
    picture: "https://example.com/caesar_salad.jpg",
  },
  {
    name: "Eggs Benedict",
    category: "Breakfast",
    estimatedPrice: 11.00,
    estimatedOrders: 120,
    likes: 105,
    picture: "https://example.com/eggs_benedict.jpg",
  },
  {
    name: "Chocolate Mousse",
    category: "Desserts",
    estimatedPrice: 7.00,
    estimatedOrders: 160,
    likes: 140,
    picture: "https://example.com/chocolate_mousse.jpg",
  },
];
\\